encuesta_medicaamigable:
    resource: "@EncuestaMedicaamigableBundle/Resources/config/routing.yml"
    prefix:   /

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

